/**
 * sf_cases_data.js — Salesforce cases data (auto-generated by sync_to_ui.py)
 * Last synced: 2026-05-14
 * Source: cardxscb--uat.sandbox.my.salesforce.com
 * Filter: Type__c = 'CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล', Status != 'Closed'
 */

const SF_CASES_DATA = [
  {
    "caseId": "500fe000005rhXAAAY",
    "caseNumber": "00163523",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005rk0KAAQ",
    "caseNumber": "00163524",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005rkhsAAA",
    "caseNumber": "00163522",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005rlIwAAI",
    "caseNumber": "00163526",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005rmbZAAQ",
    "caseNumber": "00163521",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005roFEAAY",
    "caseNumber": "00163520",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  },
  {
    "caseId": "500fe000005rpchAAA",
    "caseNumber": "00163525",
    "subject": "ขอใช้บริการ:CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "intentType": "CC - ข้อมูลส่วนตัว : เปลี่ยนแปลงชื่อ-นามสกุล",
    "status": "Open",
    "subStatus": "Pending Validation",
    "category": "การจัดการข้อมูลส่วนบุคคล",
    "customerName": "ปิติกรณ์  ใจดี",
    "citizenId": "9280635310483",
    "newFirstName": "ดารุณี",
    "newLastName": "อะฟาฟ",
    "newTitle": "อา",
    "oldName": "ถนอม",
    "documents": []
  }
];

// Store in localStorage for other scripts to use
localStorage.setItem('sfcc_sf_cases', JSON.stringify(SF_CASES_DATA));
